name: ranger_sack
version: 0.9.5
author: William DeVore
description: Sibling project to Ranger-Dart. This contains unit test, apps, node and templates. And just about anything else relating to Ranger-Dart.
homepage: https://github.com/wdevore/Ranger-Sack
documentation: https://github.com/wdevore/Ranger-Sack
dependencies:
  browser: any
  color_slider_control:
    git: git://github.com/wdevore/color_slider_control.git
  event_bus: any
  gradient_colorstops_control:
    git: git://github.com/wdevore/gradient_colorstops_control.git
  lawndart: any
  ranger:
    git: git://github.com/wdevore/ranger-dart.git
  tweenengine: any
  vector_math: any
